# Generated by Django 5.2.8 on 2025-12-26 07:19

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quartier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='TypeDepense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('categorie', models.CharField(choices=[('TRANSPORT', 'Transport'), ('LOGEMENT', 'Logement'), ('RESTAURATION', 'Restauration'), ('SERVICES', 'Services'), ('AUTRES', 'Autres')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Depense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prix', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('lieu', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('commentaire', models.TextField(blank=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='justificatifs/')),
                ('est_valide', models.BooleanField(default=True)),
                ('est_aberrant', models.BooleanField(default=False)),
                ('justification_anomalie', models.TextField(blank=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('quartier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='depenses.quartier')),
                ('type_depense', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='depenses.typedepense')),
            ],
            options={
                'verbose_name': 'Dépense',
                'verbose_name_plural': 'Dépenses',
                'ordering': ['-date'],
            },
        ),
    ]
