# Generated by Django 5.2.8 on 2025-12-28 10:34

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('depenses', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='depense',
            options={'ordering': ['-date', '-date_creation'], 'verbose_name': 'Dépense', 'verbose_name_plural': 'Dépenses'},
        ),
        migrations.AlterModelOptions(
            name='quartier',
            options={'ordering': ['nom'], 'verbose_name': 'Quartier', 'verbose_name_plural': 'Quartiers'},
        ),
        migrations.AlterModelOptions(
            name='typedepense',
            options={'ordering': ['categorie', 'nom'], 'verbose_name': 'Type de dépense', 'verbose_name_plural': 'Types de dépenses'},
        ),
        migrations.AddField(
            model_name='depense',
            name='est_mensuel',
            field=models.BooleanField(default=False, help_text='Dépense mensuelle agrégée (provenant de Kobo)'),
        ),
        migrations.AddField(
            model_name='quartier',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quartier',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='depense',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='typedepense',
            name='categorie',
            field=models.CharField(choices=[('TRANSPORT', 'Transport'), ('LOGEMENT', 'Logement'), ('RESTAURATION', 'Restauration'), ('SERVICES', 'Services'), ('AUTRES', 'Autres')], default='AUTRES', max_length=20),
        ),
        migrations.CreateModel(
            name='Sondage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kobo_id', models.CharField(help_text='Champ _id de Kobo', max_length=50, unique=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Champ _uuid')),
                ('submission_time', models.DateTimeField(help_text='Date et heure de soumission')),
                ('validation_status', models.CharField(blank=True, max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('submitted_by', models.CharField(blank=True, max_length=100)),
                ('version', models.CharField(blank=True, help_text='Champ __version__', max_length=50)),
                ('nom_et_prenom', models.CharField(blank=True, max_length=200)),
                ('age', models.PositiveIntegerField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, max_length=20)),
                ('status', models.CharField(blank=True, max_length=50)),
                ('study', models.CharField(blank=True, max_length=50)),
                ('geolocation', models.CharField(blank=True, help_text='Format: lat long', max_length=100)),
                ('logement', models.CharField(blank=True, max_length=100)),
                ('coloc', models.PositiveIntegerField(blank=True, null=True, verbose_name='Nombre de colocataires')),
                ('loyer', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('charges', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('logement_satisfaction', models.CharField(blank=True, max_length=50)),
                ('transport', models.CharField(blank=True, max_length=50)),
                ('dep_transport', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('temps_trajet', models.PositiveIntegerField(blank=True, help_text='En minutes', null=True)),
                ('diff_transport_cout', models.BooleanField(default=False)),
                ('diff_transport_insecurite', models.BooleanField(default=False)),
                ('diff_transport_retards', models.BooleanField(default=False)),
                ('diff_transport_autre', models.TextField(blank=True)),
                ('freq_repas', models.CharField(blank=True, max_length=50)),
                ('dep_alim', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('lieu_repas', models.CharField(blank=True, max_length=100)),
                ('satisfaction_repas', models.CharField(blank=True, max_length=50)),
                ('dep_internet', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('dep_loisirs', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('dep_sante', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('autres_dep', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('aug_cost', models.CharField(blank=True, max_length=50)),
                ('diff_fin', models.TextField(blank=True, verbose_name='Difficultés financières')),
                ('strategies_coloc', models.BooleanField(default=False)),
                ('strategies_repas_maison', models.BooleanField(default=False)),
                ('strategies_pied', models.BooleanField(default=False)),
                ('strategies_autre', models.TextField(blank=True)),
                ('suggestions', models.TextField(blank=True)),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sondages', to='depenses.quartier', verbose_name='Quartier')),
            ],
            options={
                'verbose_name': 'Sondage Kobo',
                'verbose_name_plural': 'Sondages Kobo',
                'ordering': ['-submission_time'],
            },
        ),
        migrations.AddField(
            model_name='depense',
            name='sondage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='depenses', to='depenses.sondage'),
        ),
    ]
