# Generated by Django 5.2.8 on 2025-12-28 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('depenses', '0002_alter_depense_options_alter_quartier_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sondage',
            name='coloc',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sondage',
            name='diff_fin',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='sondage',
            name='geolocation',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='sondage',
            name='submitted_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sondage',
            name='temps_trajet',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sondage',
            name='validation_status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='sondage',
            name='version',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
